BACKUP DATABASE [PROJECT_DB]
	TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\Backup\PROJECT_DB.bak' WITH NOFORMAT, 
	NOINIT,  
	NAME = N'PROJECT_DB-Full Database Backup', 
	SKIP, 
	NOREWIND, 
	NOUNLOAD,  
	STATS = 10
GO
